.data							#SLL IS THE MOST EFFICIENT WAY OF MULTIPLYING 2 INTEGERS AMONG THE 3 AVAILABLE METHODS BUT VERY INFLEXIBLE
							#BECAUSE ONLY POWERS OF 2 CAN BE MULTIPLIED WITH A GIVEN NUMBER
.text
	addi $s0, $zero, 6				#SUPPOSE YOU WANT TO CALCULATE 6*8
	
	sll $t0, $s0, 3					#BECAUSE 2^3=8
	
	li $v0, 1
	move $a0, $t0
	syscall